spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/smart_healthcare
    username: root
    password: ${db-password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true